package com.flashcards.android.flashcards.lib.model;

//import android.support.annotation.NonNull;

import android.arch.persistence.room.Entity;
import android.arch.persistence.room.ForeignKey;
import android.arch.persistence.room.Ignore;
import android.arch.persistence.room.PrimaryKey;
import android.support.annotation.NonNull;

import com.google.common.collect.EvictingQueue;

import java.util.List;

import static android.arch.persistence.room.ForeignKey.CASCADE;

@Entity (foreignKeys = @ForeignKey(entity = Deck.class,
        parentColumns = "deckId",
        childColumns = "deckId",
        onDelete = CASCADE))
public class Card implements Comparable<Card> {

    /* Ideally we would have a composite key of deckId and cardId, but Room does not
     * allow a composite key to be autoGenerated
     */
    @PrimaryKey(autoGenerate = true)
    @NonNull
    private int cardId;
    @NonNull
    private String deckId;
    private String question;
    private String answer;

    private int attempts;   //Invariant: must always stay positive
    private int correct;
    private EvictingQueue<Boolean> lastTen;     // Pushes out old elements if size exceeds 10
    private int learntScore;


    /**
     * A class to store Flash cards objects.
     * A corresponding Progress Object must be setup after a Card is created.
     * @param deckId
     * @param question
     * @param answer
     *
     */
    public Card(String deckId, String question, String answer) {
        this.deckId = deckId;
        this.question = question;
        this.answer = answer;
    }

    /**
     * For creating an empty card
     * @param deckId
     */
    @Ignore
    public Card (String deckId) {
        this.deckId = deckId;
        this.question = "";
        this.answer = "";
        this.attempts = 0;
        this.correct = 0;
        this.lastTen = EvictingQueue.create(10);
        this.learntScore = 100;
    }

    //TODO: progress has to be manually set once the card is created

    public int getCardId() {
        return cardId;
    }

    public void setCardId(int cardId) {
        this.cardId = cardId;
    }

    public String getDeckId() {
        return deckId;
    }

    public void setDeckId(String deckId) {
        this.deckId = deckId;
    }

    public String getQuestion() {
        return question;
    }

    public void setQuestion(String question) {
        this.question = question;
    }

    public String getAnswer() {
        return answer;
    }

    public void setAnswer(String answer) {
        this.answer = answer;
    }

    public int getAttempts() {
        return attempts;
    }

    public void setAttempts(int attempts) {
        this.attempts = attempts;
    }

    public void incAttempts() {
        attempts++;
    }

    public int getCorrect() {
        return correct;
    }

    public void setCorrect(int correct) {
        this.correct = correct;
    }

    public void incCorrect() {
        correct++;
    }

    public EvictingQueue<Boolean> getLastTen() {
        return lastTen;
    }

    public void setLearntScore(int learntScore) {
        this.learntScore = learntScore;
    }

    public void setLastTen(EvictingQueue<Boolean> lastTen) {
        this.lastTen = lastTen;
    }

    public void setLastTen(List<Boolean> list) {
        lastTen.addAll(list);
    }

    public void addAnswer(Boolean answer) {
        lastTen.offer(answer);
    }

    public int getLearntScore(int deckSize) {
        learntScore = Progress.generateLearntScore(deckSize, this);
        return learntScore;
    }

    public int getLearntScore() {
        return learntScore;
    }


    //TODO: test the comparator

    /** Comparator for ranking cards by 'learnt score'
     *
     * @param o Card being compared
     * @return integer corresponding to the comparison of the two cards
     */
    @Override
    public int compareTo(Card o) {
        Integer thisScore = this.getLearntScore();
        Integer otherScore = o.getLearntScore();

        return thisScore.compareTo(otherScore);
    }

    @Override
    public boolean equals(Object o) {
        if (o == null) {
            return false;
        } else {
            return ((Integer) this.cardId).equals(((Card) o).getCardId());
        }
    }


    @Override
    public String toString() {
        return "Question='" + question + '\'' +
                ", Answer='" + answer + '\'';
    }

}